# Generated by Django 5.2.12 on 2026-03-08 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipes', '0001_initial'),
        ('jogadores', '0001_initial'),
        ('partidas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=100)),
                ('minuto', models.PositiveIntegerField(default=0)),
                ('segundo', models.PositiveIntegerField(default=0)),
                ('posicao_x', models.FloatField(blank=True, null=True)),
                ('posicao_y', models.FloatField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipes.equipe')),
                ('jogador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jogadores.jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='partidas.partida')),
            ],
            options={
                'ordering': ['minuto', 'segundo', 'id'],
            },
        ),
    ]
