# Generated by Django 5.2.12 on 2026-03-08 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_clipe', models.CharField(max_length=500)),
                ('duracao', models.PositiveIntegerField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clipes', to='eventos.evento')),
            ],
        ),
    ]
