# Generated by Django 5.2.12 on 2026-03-08 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competicao', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('tipo_video', models.CharField(choices=[('upload', 'Upload'), ('link', 'Link')], max_length=10)),
                ('url_video', models.CharField(blank=True, max_length=500)),
                ('tamanho_armazenamento_video', models.BigIntegerField(default=0)),
                ('equipe_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_casa', to='equipes.equipe')),
                ('equipe_fora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_fora', to='equipes.equipe')),
            ],
        ),
    ]
