# Generated by Django 5.2.12 on 2026-03-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=100)),
                ('brasao', models.ImageField(blank=True, null=True, upload_to='equipes/brasoes/')),
            ],
        ),
    ]
