# Generated by Django 5.2.12 on 2026-03-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='pais',
        ),
        migrations.AddField(
            model_name='equipe',
            name='categoria_organizacao',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='equipe',
            name='informacoes_analista',
            field=models.TextField(blank=True),
        ),
    ]
