# Generated by Django 5.2.12 on 2026-03-08 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('posicao', models.CharField(max_length=50)),
                ('idade', models.PositiveIntegerField()),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='equipes.equipe')),
            ],
        ),
    ]
