# Generated by Django 5.2.12 on 2026-03-08 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0002_remove_equipe_pais_equipe_categoria_organizacao_and_more'),
        ('jogadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='categoria_organizacao',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='jogador',
            name='independente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jogador',
            name='informacoes_analista',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='equipes.equipe'),
        ),
    ]
