# Generated by Django 5.2.12 on 2026-03-08 05:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogadores", "0002_jogador_categoria_organizacao_jogador_independente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jogador",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="jogadores/fotos/"),
        ),
        migrations.CreateModel(
            name="AvaliacaoJogador",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_avaliacao", models.DateTimeField(default=django.utils.timezone.now)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "tecnica",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]
                    ),
                ),
                (
                    "fisico",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]
                    ),
                ),
                (
                    "velocidade",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]
                    ),
                ),
                (
                    "inteligencia_tatica",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]
                    ),
                ),
                (
                    "competitividade",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]
                    ),
                ),
                (
                    "potencial",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]
                    ),
                ),
                (
                    "jogador",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="avaliacoes", to="jogadores.jogador"),
                ),
            ],
            options={
                "verbose_name": "avaliacao do jogador",
                "verbose_name_plural": "avaliacoes dos jogadores",
                "ordering": ["-data_avaliacao", "-id"],
            },
        ),
    ]
